#!/usr/bin/env bash
# Stop hook: keep one-pager infographics current without starting design work.
# A project's artifacts/infographic.html is "stale" when plan.md or tasks.md is
# newer than it. Only projects with status ready / in-progress and a real
# (non-stub) plan.md are considered — done projects are left alone. To avoid
# nagging about unrelated old work, the stale source must also have changed during
# this session. Each unchanged source revision is handled at most once.
#
# Hub resolution matches every other hook: $TODO_HUB (default ~/todo), never the
# current working directory. To stay quiet in unrelated repos, a stale project is
# handled only when the session's working directory is the hub itself or sits
# inside that project's target repo (the `repo` column), including the
# <repo>-wt/* worktrees that /todo-execute creates.
#
# Each stale project goes through the todo-infographic refresh helper's `inspect`:
#   fresh / stub      -> nothing.
#   fast-refresh      -> the hook runs `apply` + `verify` itself; silent on success.
#   semantic-refresh  -> block, naming only those projects: a small inline prose patch.
#   legacy-migration, full-build, or any helper error -> a non-blocking notice that
#                        names `/todo-infographic <short-name>`; the hook never starts
#                        a full build or legacy migration.
#
# Output contract (Stop hook, valid for Claude Code and Codex): print nothing to
# allow the stop; {"systemMessage":"..."} for a notice; {"decision":"block",
# "reason":"..."} (plus "systemMessage" when notices exist) to continue the turn.
set -euo pipefail

HUB="${TODO_HUB:-$HOME/todo}"
case "$HUB" in "~"*) HUB="${HOME}${HUB#\~}" ;; esac
INDEX="$HUB/index.md"

# Read the hook payload; if we're already inside a stop-hook continuation, don't
# re-trigger — avoids a loop if generation ever fails to refresh the file.
payload="$(cat 2>/dev/null || true)"
case "$payload" in
  *'"stop_hook_active":true'*|*'"stop_hook_active": true'*) exit 0 ;;
esac

# Stop payload fields are simple JSON strings generated by Claude Code. Avoid a
# jq dependency: session IDs and transcript paths do not contain literal quotes.
json_string_field() {
  local field="$1"
  local match
  match="$(printf '%s\n' "$payload" |
    grep -Eo "\"${field}\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" |
    head -n 1 || true)"
  printf '%s\n' "$match" |
    sed -n "s/^\"${field}\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\"$/\1/p"
}

session_id="$(json_string_field session_id)"
transcript_path="$(json_string_field transcript_path)"
case "$transcript_path" in "~/"*) transcript_path="${HOME}/${transcript_path#\~/}" ;; esac

# Without a stable session boundary we cannot distinguish current work from old
# repository-wide staleness. Fail quiet rather than interrupt an unrelated turn.
case "$session_id" in *[!A-Za-z0-9._-]*|'') exit 0 ;; esac
[ -f "$transcript_path" ] || exit 0

# File birth time is the session boundary because Claude creates one transcript
# per session. BSD/macOS exposes it as %B; GNU stat exposes it as %W.
session_started="$(stat -f %B "$transcript_path" 2>/dev/null || stat -c %W "$transcript_path" 2>/dev/null || echo 0)"
case "$session_started" in ''|*[!0-9]*) exit 0 ;; esac
[ "$session_started" -gt 0 ] || exit 0

state_root="${TODO_INFOGRAPHIC_HOOK_STATE_DIR:-${TMPDIR:-/tmp}/todo-list-infographic-hook}"
session_state="$state_root/$session_id"

[ -f "$INDEX" ] || exit 0

CWD="${CLAUDE_PROJECT_DIR:-$PWD}"
in_hub=0
case "$CWD" in
  "$HUB"|"$HUB"/*) in_hub=1 ;;
esac

# Portable mtime (BSD/macOS then GNU/Linux).
mtime() { stat -f %m "$1" 2>/dev/null || stat -c %Y "$1" 2>/dev/null || echo 0; }

# Trim a registry cell and drop Markdown code backticks.
cell() {
  local value="${1//\`/}"
  value="${value#"${value%%[![:space:]]*}"}"
  printf '%s' "${value%"${value##*[![:space:]]}"}"
}

stale=()
# Pull "path|repo|status" for every project row in index.md (skips header/separator rows).
while IFS='|' read -r _ shortname path repo status _rest; do
  shortname="$(cell "$shortname")"
  case "$shortname" in *[!A-Za-z0-9._-]*|''|.|..) continue ;; esac
  path="$(cell "$path")"
  case "$path" in /*|*[!A-Za-z0-9._/-]*|''|..|../*|*/../*|*/..) continue ;; esac
  repo="$(cell "$repo")"
  status="$(cell "$status")"
  case "$status" in
    ready|in-progress) ;;
    *) continue ;;
  esac

  # Session scope: a hub session sees every project; any other session sees only
  # the project whose target repo (or its -wt worktree) contains the cwd.
  if [ "$in_hub" -eq 0 ]; then
    case "$repo" in
      "~/"*|"/"*) repo="${repo/#\~/$HOME}" ;;
      *) continue ;;
    esac
    case "$CWD" in
      "$repo"|"$repo"/*|"$repo"-wt/*) ;;
      *) continue ;;
    esac
  fi

  plan="$HUB/$path/plan.md"
  tasks="$HUB/$path/tasks.md"
  info="$HUB/$path/artifacts/infographic.html"

  [ -f "$plan" ] || continue
  # Skip unfilled template stubs.
  grep -q "What success looks like in one sentence." "$plan" 2>/dev/null && continue

  pt="$(mtime "$plan")"
  tt="$(mtime "$tasks")"
  # Old stale inputs are not evidence that this session owns the project.
  [ "$pt" -gt "$session_started" ] || [ "$tt" -gt "$session_started" ] || continue

  if [ -f "$info" ]; then
    it="$(mtime "$info")"
    [ "$pt" -gt "$it" ] || [ "$tt" -gt "$it" ] || continue
  fi

  source_revision="$pt"
  [ "$tt" -gt "$source_revision" ] && source_revision="$tt"
  marker="$session_state/$shortname"
  reported_revision=0
  if [ -f "$marker" ]; then
    read -r reported_revision < "$marker" || reported_revision=0
    case "$reported_revision" in ''|*[!0-9]*) reported_revision=0 ;; esac
  fi
  [ "$source_revision" -gt "$reported_revision" ] || continue

  stale+=("$shortname|$path|$status")
  mkdir -p "$session_state"
  printf '%s\n' "$source_revision" > "$marker"
done < <(grep -E '^\|' "$INDEX" | grep -Ev '^\| *short-name' | grep -Ev '^\|[ :|-]+\|?[ ]*$')

[ "${#stale[@]}" -gt 0 ] || exit 0

hook_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
helper="$hook_dir/../skills/todo-infographic/scripts/refresh-infographic.py"
python="${TODO_INFOGRAPHIC_PYTHON:-python3}"
today="$(date +%F)"
# hooks.json allows 15s; leave headroom for the scan and the JSON output.
budget="${TODO_INFOGRAPHIC_HOOK_BUDGET_SECONDS:-10}"

# Helper output becomes one short printable line; JSON strings escape \ and ".
one_line() {
  printf '%s\n' "$1" | head -n 1 | sed "s/ERROR$(printf '\t')//" | tr '\t' ' ' |
    LC_ALL=C tr -cd '[:print:]' | cut -c1-160
}
json_text() { printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'; }

semantic=()
message=""
notice() {
  message="${message:+$message; }$1 ($(one_line "$2")): run /todo-infographic $1"
}

for entry in "${stale[@]}"; do
  IFS='|' read -r shortname path status <<< "$entry"
  if [ "$SECONDS" -ge "$budget" ]; then
    notice "$shortname" "not checked before the Stop-hook time limit"
    continue
  fi
  if [ ! -f "$helper" ] || ! command -v "$python" >/dev/null 2>&1; then
    notice "$shortname" "refresh helper unavailable"
    continue
  fi
  project="$HUB/$path"
  info="$project/artifacts/infographic.html"
  if ! manifest="$("$python" "$helper" inspect "$project" --html "$info" \
      --date "$today" --status "$status" 2>&1 </dev/null)"; then
    notice "$shortname" "helper error: $manifest"
    continue
  fi
  mode="$(printf '%s\n' "$manifest" |
    sed -n 's/^  "mode": "\([a-z-]*\)",\{0,1\}$/\1/p' | head -n 1)"
  case "$mode" in
    fresh|stub) ;;
    fast-refresh)
      if ! result="$("$python" "$helper" apply "$project" --html "$info" \
          --date "$today" --status "$status" 2>&1 </dev/null)" ||
         ! result="$("$python" "$helper" verify "$project" --html "$info" 2>&1 </dev/null)"; then
        notice "$shortname" "fast refresh failed: $result"
      fi
      ;;
    semantic-refresh) semantic+=("$shortname") ;;
    legacy-migration|full-build) notice "$shortname" "$mode needed" ;;
    *) notice "$shortname" "helper error: unknown mode '${mode:-none}'" ;;
  esac
done

[ -z "$message" ] || message="$(json_text "Infographic not refreshed automatically: $message.")"

if [ "${#semantic[@]}" -gt 0 ]; then
  names="$(json_text "${semantic[*]}")"
  reason="Infographic prose is stale after this session's plan.md or tasks.md edits for: \
${names}. For each listed project only, follow the todo-infographic semantic-refresh \
path: inspect, write the small inline prose patch for the changed content leaves \
yourself, apply it, and verify. Do not start a full build or legacy migration."
  if [ -n "$message" ]; then
    printf '{"decision":"block","reason":"%s","systemMessage":"%s"}\n' "$reason" "$message"
  else
    printf '{"decision":"block","reason":"%s"}\n' "$reason"
  fi
elif [ -n "$message" ]; then
  printf '{"systemMessage":"%s"}\n' "$message"
fi
exit 0
