#!/usr/bin/env bash
# Stop hook: nudge the agent to (re)generate one-pager infographics that are missing
# or stale. A project's artifacts/infographic.html is "stale" when plan.md or
# tasks.md is newer than it. Only projects with status ready / in-progress and a
# real (non-stub) plan.md are considered — done projects are left alone. To avoid
# nagging about unrelated old work, the stale source must also have changed during
# this Claude session. Each unchanged source revision is reported at most once.
#
# Hub resolution matches every other hook: $TODO_HUB (default ~/todo), never the
# current working directory. To stay quiet in unrelated repos, a stale project is
# reported only when the session's working directory is the hub itself or sits
# inside that project's target repo (the `repo` column), including the
# <repo>-wt/* worktrees that /todo-execute creates.
#
# Output contract (Stop hook): emit {"decision":"block","reason":"..."} to keep the
# turn going so the agent regenerates; emit nothing (exit 0) to allow the stop.
set -euo pipefail

HUB="${TODO_HUB:-$HOME/todo}"
case "$HUB" in "~"*) HUB="${HOME}${HUB#\~}" ;; esac
INDEX="$HUB/index.md"

# Read the hook payload; if we're already inside a stop-hook continuation, don't
# re-trigger — avoids a loop if generation ever fails to refresh the file.
payload="$(cat 2>/dev/null || true)"
case "$payload" in
  *'"stop_hook_active":true'*|*'"stop_hook_active": true'*) exit 0 ;;
esac

# Stop payload fields are simple JSON strings generated by Claude Code. Avoid a
# jq dependency: session IDs and transcript paths do not contain literal quotes.
json_string_field() {
  local field="$1"
  local match
  match="$(printf '%s\n' "$payload" |
    grep -Eo "\"${field}\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" |
    head -n 1 || true)"
  printf '%s\n' "$match" |
    sed -n "s/^\"${field}\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\"$/\1/p"
}

session_id="$(json_string_field session_id)"
transcript_path="$(json_string_field transcript_path)"
case "$transcript_path" in "~/"*) transcript_path="${HOME}/${transcript_path#\~/}" ;; esac

# Without a stable session boundary we cannot distinguish current work from old
# repository-wide staleness. Fail quiet rather than interrupt an unrelated turn.
case "$session_id" in *[!A-Za-z0-9._-]*|'') exit 0 ;; esac
[ -f "$transcript_path" ] || exit 0

# File birth time is the session boundary because Claude creates one transcript
# per session. BSD/macOS exposes it as %B; GNU stat exposes it as %W.
session_started="$(stat -f %B "$transcript_path" 2>/dev/null || stat -c %W "$transcript_path" 2>/dev/null || echo 0)"
case "$session_started" in ''|*[!0-9]*) exit 0 ;; esac
[ "$session_started" -gt 0 ] || exit 0

state_root="${TODO_INFOGRAPHIC_HOOK_STATE_DIR:-${TMPDIR:-/tmp}/todo-list-infographic-hook}"
session_state="$state_root/$session_id"

[ -f "$INDEX" ] || exit 0

CWD="${CLAUDE_PROJECT_DIR:-$PWD}"
in_hub=0
case "$CWD" in
  "$HUB"|"$HUB"/*) in_hub=1 ;;
esac

# Portable mtime (BSD/macOS then GNU/Linux).
mtime() { stat -f %m "$1" 2>/dev/null || stat -c %Y "$1" 2>/dev/null || echo 0; }

stale=""
# Pull "path|repo|status" for every project row in index.md (skips header/separator rows).
while IFS='|' read -r _ shortname path repo status _rest; do
  shortname="$(echo "$shortname" | xargs)"
  case "$shortname" in *[!A-Za-z0-9._-]*|'') continue ;; esac
  path="$(echo "$path" | xargs)"
  path="${path//\`/}"
  repo="$(echo "$repo" | xargs)"
  repo="${repo//\`/}"
  status="$(echo "$status" | xargs)"
  case "$status" in
    ready|in-progress) ;;
    *) continue ;;
  esac

  # Session scope: a hub session sees every project; any other session sees only
  # the project whose target repo (or its -wt worktree) contains the cwd.
  if [ "$in_hub" -eq 0 ]; then
    case "$repo" in
      "~/"*|"/"*) repo="${repo/#\~/$HOME}" ;;
      *) continue ;;
    esac
    case "$CWD" in
      "$repo"|"$repo"/*|"$repo"-wt/*) ;;
      *) continue ;;
    esac
  fi

  plan="$HUB/$path/plan.md"
  tasks="$HUB/$path/tasks.md"
  info="$HUB/$path/artifacts/infographic.html"

  [ -f "$plan" ] || continue
  # Skip unfilled template stubs.
  grep -q "What success looks like in one sentence." "$plan" 2>/dev/null && continue

  pt="$(mtime "$plan")"
  tt="$(mtime "$tasks")"
  # Old stale inputs are not evidence that this session owns the project.
  [ "$pt" -gt "$session_started" ] || [ "$tt" -gt "$session_started" ] || continue

  if [ -f "$info" ]; then
    it="$(mtime "$info")"
    [ "$pt" -gt "$it" ] || [ "$tt" -gt "$it" ] || continue
  fi

  source_revision="$pt"
  [ "$tt" -gt "$source_revision" ] && source_revision="$tt"
  marker="$session_state/$shortname"
  reported_revision=0
  if [ -f "$marker" ]; then
    read -r reported_revision < "$marker" || reported_revision=0
    case "$reported_revision" in ''|*[!0-9]*) reported_revision=0 ;; esac
  fi
  [ "$source_revision" -gt "$reported_revision" ] || continue

  stale="$stale $shortname"
  mkdir -p "$session_state"
  printf '%s\n' "$source_revision" > "$marker"
done < <(grep -E '^\|' "$INDEX" | grep -Ev '^\| *short-name' | grep -Ev '^\|[ :|-]+\|?[ ]*$')

stale="$(echo "$stale" | xargs)"
[ -z "$stale" ] && exit 0

reason="One-pager infographic(s) became stale from plan.md or tasks.md changes in \
this session for: ${stale}. Invoke the todo-infographic skill only for the listed \
project(s); it writes artifacts/infographic.html and updates the infographic column \
in index.md."

# Emit the block decision as JSON (printf keeps it valid without jq).
printf '{"decision":"block","reason":"%s"}\n' "$reason"
exit 0
